### PR TITLE
Latest Arch ISO since August doesn't work with timedatectl

### PR DESCRIPTION
**Pull request by saboooor**

### CODE REVIEW

**Comment by nunopenim** [comment]
sudo used to be like that, then they removed the : part 🥲 systohc method was known, but... 10 times harder. Thanks

**Comment by nunopenim** [comment]
@saboooor mf put your name on the top of the guide too

**Comment by saboooor** [comment]
> @saboooor mf put your name on the top of the guide too

why💀

**Comment by nunopenim** [comment]
> why💀

I'm telling you to

**Comment by saboooor** [comment]
> I'm telling you to

but why

**Comment by nunopenim** [comment]
> > I'm telling you to
> 
> but why

YOU STALE TOMATO, IT AIN'T MY AUTHORSHIP EXCLUSIVELY AAAAAAAA

**Comment by saboooor** [comment]
> YOU STALE TOMATO, IT AIN'T MY AUTHORSHIP EXCLUSIVELY AAAAAAAA

BUT WHAT DID I DO TO DESERVE MY NAME THERE
WHY AM I AUTHOR AAAAAAAAA

**Pull request merged**
